### ISSUE TITLE
Load example activities from the educationplatform-examples 

### ISSUE THREAD

**Issue by barnettwilliam** [mdenet/educationplatform-docker#19]
Load example activity files from the mdenet/educationplatform-examples repo and remove the separate `mdenet-test-activities` container. 

https://github.com/mdenet/educationplatform/issues/26#issuecomment-1741119726

**Comment by arturboronat** [comment]
When the docker image is created, all services in platform tools are compiled, as shown in [this line](https://github.com/mdenet/educationplatform-tooltemplate/blob/4dbd3d8e22b599945248753a4b95017ad7e11f21/static.helloworld/Dockerfile#L7).  This is a bit of a burden when a tool is independent of Eclipse since the build still requires to pull Eclipse dependencies via Tycho because all tools shipped with the platform are being compiled. Could a target 'core' be defined instead of using 'all' in order to minimise the required dependencies?
